-- Migration 011: Create spec_aliases table and seed with defaults
CREATE TABLE IF NOT EXISTS spec_aliases (
  id         INT          NOT NULL AUTO_INCREMENT,
  char_class VARCHAR(50)  NOT NULL,
  alias      VARCHAR(100) NOT NULL,
  canonical  VARCHAR(100) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_class_alias (char_class, alias)
);

INSERT IGNORE INTO spec_aliases (char_class, alias, canonical) VALUES
  ('druid', 'balance',        'Balance'),
  ('druid', 'boomkin',        'Balance'),
  ('druid', 'moonkin',        'Balance'),
  ('druid', 'owl',            'Balance'),
  ('druid', 'boomy',          'Balance'),
  ('druid', 'boom',           'Balance'),
  ('druid', 'laser chicken',  'Balance'),
  ('druid', 'lazer chicken',  'Balance'),
  ('druid', 'feral',          'Feral'),
  ('druid', 'cat',            'Feral'),
  ('druid', 'kitty',          'Feral'),
  ('druid', 'feral cat',      'Feral'),
  ('druid', 'bear',           'Feral'),
  ('druid', 'feral bear',     'Feral'),
  ('druid', 'beardin',        'Feral'),
  ('druid', 'guardian',       'Feral'),
  ('druid', 'restoration',    'Restoration'),
  ('druid', 'resto',          'Restoration'),
  ('druid', 'restro',         'Restoration'),
  ('druid', 'tree',           'Restoration'),
  ('druid', 'treant',         'Restoration'),

  ('death knight', 'blood',           'Blood (Tank)'),
  ('death knight', 'blood tank',      'Blood (Tank)'),
  ('death knight', 'blood dk tank',   'Blood (Tank)'),
  ('death knight', 'blood dps',       'Blood (DPS)'),
  ('death knight', 'blood dk dps',    'Blood (DPS)'),
  ('death knight', 'frost tank',      'Frost (Tank)'),
  ('death knight', 'frost dk tank',   'Frost (Tank)'),
  ('death knight', 'frost dps',       'Frost (DPS)'),
  ('death knight', 'frost dk dps',    'Frost (DPS)'),
  ('death knight', 'unholy',          'Unholy'),
  ('death knight', 'uh',              'Unholy'),
  ('death knight', 'unholy dk',       'Unholy'),

  ('hunter', 'beast mastery',   'Beast Mastery'),
  ('hunter', 'bm',              'Beast Mastery'),
  ('hunter', 'beastmaster',     'Beast Mastery'),
  ('hunter', 'beast master',    'Beast Mastery'),
  ('hunter', 'bm hunter',       'Beast Mastery'),
  ('hunter', 'marksmanship',    'Marksmanship'),
  ('hunter', 'mm',              'Marksmanship'),
  ('hunter', 'marks',           'Marksmanship'),
  ('hunter', 'marksman',        'Marksmanship'),
  ('hunter', 'mm hunter',       'Marksmanship'),
  ('hunter', 'survival',        'Survival'),
  ('hunter', 'sv',              'Survival'),
  ('hunter', 'surv',            'Survival'),
  ('hunter', 'survival hunter', 'Survival'),
  ('hunter', 'surv hunter',     'Survival'),

  ('mage', 'arcane',      'Arcane'),
  ('mage', 'arcane mage', 'Arcane'),
  ('mage', 'arc',         'Arcane'),
  ('mage', 'fire',        'Fire'),
  ('mage', 'fire mage',   'Fire'),
  ('mage', 'frost',       'Frost'),
  ('mage', 'frost mage',  'Frost'),
  ('mage', 'frostfire',   'Frostfire'),
  ('mage', 'ffb',         'Frostfire'),

  ('paladin', 'holy',             'Holy'),
  ('paladin', 'holy paladin',     'Holy'),
  ('paladin', 'hpala',            'Holy'),
  ('paladin', 'hpal',             'Holy'),
  ('paladin', 'holy pally',       'Holy'),
  ('paladin', 'protection',       'Protection'),
  ('paladin', 'prot',             'Protection'),
  ('paladin', 'prot paladin',     'Protection'),
  ('paladin', 'prot pala',        'Protection'),
  ('paladin', 'tankadin',         'Protection'),
  ('paladin', 'retribution',      'Retribution'),
  ('paladin', 'ret',              'Retribution'),
  ('paladin', 'retri',            'Retribution'),
  ('paladin', 'ret paladin',      'Retribution'),
  ('paladin', 'ret pala',         'Retribution'),
  ('paladin', 'ret pally',        'Retribution'),

  ('priest', 'discipline',   'Discipline'),
  ('priest', 'disc',         'Discipline'),
  ('priest', 'disc priest',  'Discipline'),
  ('priest', 'holy',         'Holy'),
  ('priest', 'holy priest',  'Holy'),
  ('priest', 'shadow',       'Shadow'),
  ('priest', 'shadow priest','Shadow'),
  ('priest', 'spriest',      'Shadow'),

  ('rogue', 'assassination',  'Assassination'),
  ('rogue', 'mutilate',       'Assassination'),
  ('rogue', 'muti',           'Assassination'),
  ('rogue', 'mut',            'Assassination'),
  ('rogue', 'assassin',       'Assassination'),
  ('rogue', 'assas',          'Assassination'),
  ('rogue', 'combat',         'Combat'),
  ('rogue', 'combat rogue',   'Combat'),
  ('rogue', 'subtlety',       'Subtlety'),
  ('rogue', 'sub',            'Subtlety'),
  ('rogue', 'sub rogue',      'Subtlety'),

  ('shaman', 'elemental',       'Elemental'),
  ('shaman', 'ele',             'Elemental'),
  ('shaman', 'elem',            'Elemental'),
  ('shaman', 'ele shaman',      'Elemental'),
  ('shaman', 'elem shaman',     'Elemental'),
  ('shaman', 'enhancement',     'Enhancement'),
  ('shaman', 'enh',             'Enhancement'),
  ('shaman', 'enhance',         'Enhancement'),
  ('shaman', 'enh shaman',      'Enhancement'),
  ('shaman', 'restoration',     'Restoration'),
  ('shaman', 'resto',           'Restoration'),
  ('shaman', 'restro',          'Restoration'),
  ('shaman', 'rsham',           'Restoration'),
  ('shaman', 'resto shaman',    'Restoration'),

  ('warlock', 'affliction',   'Affliction'),
  ('warlock', 'affli',        'Affliction'),
  ('warlock', 'affl',         'Affliction'),
  ('warlock', 'demonology',   'Demonology'),
  ('warlock', 'demo',         'Demonology'),
  ('warlock', 'demon',        'Demonology'),
  ('warlock', 'destruction',  'Destruction'),
  ('warlock', 'destro',       'Destruction'),
  ('warlock', 'destruct',     'Destruction'),

  ('warrior', 'arms',          'Arms'),
  ('warrior', 'arms warrior',  'Arms'),
  ('warrior', 'fury',          'Fury'),
  ('warrior', 'fury warrior',  'Fury'),
  ('warrior', 'protection',    'Protection'),
  ('warrior', 'prot',          'Protection'),
  ('warrior', 'prot warrior',  'Protection'),
  ('warrior', 'prot war',      'Protection');
